services:
  postgres:
    container_name: postgres_go
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - "5432:5432"
